## 1. Averaging Neighboring Values COO

In [5]:
'''
n: size

'''
n = 5
total = n**2

num = 2
rc = 2*n - 1 #how many data
fsize = 64
intsize = 32
tsize = (fsize*rc + intsize*rc*2)/8
tsize

144.0

In [1]:
'''
n: size
num:  -2 -1 0 1 2
'''
n = 6
p5 = 5
fsize = 64
intsize = 32

total = n**2
rc = (p5-2 + p5-1 +p5)*2 #how many data

tsize = (fsize*rc + intsize*rc*2)/8
tsize

384.0

## 2. CSR vs Dense format

In [3]:
import sympy as sp
from sympy import *
'''
n: size*size of matrix
dsto: Dense Representation
dcsr: CSR format
'''
n = 90
dsto = 4
dcsr = 4

S = pow(n,2)

dense = dsto*S
x = sp.var('x')#num of non-zero element

csr = (2*x + n + 1)*4

result = solve(csr - dense, x)
floor(float(result[0]))

4004

## 3. Representing a Sparse Matrix in COO Format

In [19]:
n = 5
total = n**2
rc = 7 #how many data
fsize = 64
intsize = 32
tsize = (fsize*rc + intsize*rc*2)/8
tsize

112.0

## 4. Construct a Matrix from CSR Format

In [28]:
import scipy.sparse as sparse
data = [0.70, 0.30, 0.40, 0.60, 0.50, 0.80, 0.10]
rowptr = [0,1,4,5,7]
col = [3,1,2,3,0,0,3]
n = len(rowptr) - 1
sparse.csr_matrix((data,col,rowptr), shape =(n,n)).toarray()

array([[0. , 0. , 0. , 0.7],
       [0. , 0.3, 0.4, 0.6],
       [0.5, 0. , 0. , 0. ],
       [0.8, 0. , 0. , 0.1]])

## 5.Representing a Sparse Matrix in CSR Format

In [4]:
import scipy.sparse as sparse

A = [
    [0,0,0,6.2,0],
    [0,0,0,2.6,0],
    [6.6,0,0,0,0],
    [5.00,8.90,2.60,0,0],
    [6.00,0,0,0,0]]
fsize = 64
intsize = 32
# Step1: information
A = sparse.coo_matrix(A)
A = A.tocsr()
print(A.data)
print(A.data.dtype, 'Length: ', len(A.data))
print('-')
print(A.indptr)
print(A.indptr.dtype, 'Length: ', len(A.indptr))
print('-')
print(A.indices)
print(A.indices.dtype, 'Length: ', len(A.indices))
# Step2: type
n = len(A.indptr) - 1 # number of col
rc = len(A.data) #how many data

tsize = (fsize*rc + intsize*(n+1+rc))/8
tsize

[6.2 2.6 6.6 5.  8.9 2.6 6. ]
float64 Length:  7
-
[0 1 2 3 6 7]
int32 Length:  6
-
[3 3 0 0 1 2 0]
int32 Length:  7


108.0

## C1:  Storing Player Attributes in a COO Matrix

In [5]:
'''
row is player
col is attribute
'''
import numpy as np
data = []
row = []
col = []

count = 0
for i in player_attributes:#work through each player
    for key in i: #walk through att of this player
        
        for idx in range(len(all_attributes)): #locate
            if (key == all_attributes[idx]):
                data.append(i[key])
                row.append(count)
                col.append(idx)
                
    count+=1

NameError: name 'player_attributes' is not defined