## 1.Estimate Condition Number

In [38]:
pb = -5
rx = 0.04
con = rx/pow(10, pb)
con

3999.9999999999995

## 2.Approximate Matrix Condition Number

In [91]:
a1 = 2
b1 = 4
c1 = 6
a2 = 10
b2 = 80
c2 = 180

a = a2/a1
b = b2/b1
c = c2/c1
print(max(a,b,c)/min(a,b,c))
#最大norm/最小norm=>最大cond

6.0


## 3. PageRank Transition Matrix

In [3]:
import numpy as np
N = 4
df = 0.9
A = np.array([
    [0,1,0,0],
    [1,0,1,0],
    [1,0,0,0],
    [0,0,1,0]
])

def sum_one(arr:np.ndarray):
    copy = np.zeros([4,4])
    s = sum(arr)
    new = arr.T
    
    for i in range(len(new)):
        if s[i] != 0:
            copy[i] = new[i]/s[i]
    return copy.T

B = sum_one(A)
#print(B)
C = np.zeros((N,N))
for i in range(len(B)):
    for j in range(len(B[i])):
        if sum(B.T[j]) != 0:
            C[i][j] = df*B[i][j] + (1-df)/N
        else: C[i][j] = 1/N #why?
C

array([[0.025, 0.925, 0.025, 0.25 ],
       [0.475, 0.025, 0.475, 0.25 ],
       [0.475, 0.025, 0.025, 0.25 ],
       [0.025, 0.025, 0.475, 0.25 ]])

## 4.1 Representing a Sparse Matrix in COO Format

In [36]:
#普通matrix->COO
import scipy.sparse as sparse
A = [[0.9,1.3,0.4,0],
     [0,0,0,0],
     [0,0,0,0],
     [0,0.6,0,1.2]
    ]
# Step1: information
A = sparse.coo_matrix(A)
print('Data: ', A.data)
print('-')
print('Row: ', A.row)
print('-')
print('Col: ', A.col)


[0.9 1.3 0.4 0.6 1.2]
Data:  [0.9 1.3 0.4 0.6 1.2]
-
Row:  [0 0 0 3 3]
-
Col:  [0 1 2 1 3]


## 4.2 Representing a Sparse Matrix in CSR Format

In [76]:
import scipy.sparse as sparse
A = [[0.8,0,0,0.5],
     [0,0,0,0.4],
     [0.3,0.1,0,0.7],
     [0.3,0,0,0.6]
    ]
# Step1: information
A = sparse.csr_matrix(A)
print('Data: ', A.data)
print('-')
print('Rowptr: ', A.indptr)
print('-')
print('Col: ', A.indices)

Data:  [0.8 0.5 0.4 0.3 0.1 0.7 0.3 0.6]
-
Rowptr:  [0 2 3 6 8]
-
Col:  [0 3 3 0 1 3 0 3]


## 5. Finding the Eigenvalues of Transformed Matrices

In [35]:
'''
find eigenvalue of ((c1*A-c2*I)^(-1))^(p)
'''
a1e = 8 #eigen1
a2e = 7 #eigen2
c1 = 4
c2 = 4
p = 2

e1 = 1/(c1*a1e - c2)
e2 = 1/(c1*a2e - c2)

e11 = pow(e1,p)
e22 = pow(e2,p)

print(max(e11, e22))

0.001736111111111111


## 6.Matrix Condition Number: Changing the Right-Hand Side

In [15]:
'''
b: power
A: cond A
B: cond B
'''
b = -4
A = 4
B = 16

x = A*B*pow(10,b)
x

0.0064

## 6.2 Matrix Condition Number: Changing the Matrix

In [88]:
# 2 8
A = -11
cA = 2
x =  A+cA
x

-9

## 7. Power Iteration

In [28]:
import numpy as np
from numpy.linalg import eig
A = np.array([
    [1,-8],
    [0,4]
])
pl = -3 #power least

#S1: find eigenvalues
w,v=eig(A)
eva1 = max(w)
eva2 = min(w)
#print(eva1, eva2)
#S2 get iterations
num = 1 #number of iterations（初始）
it = abs(eva2/eva1) #初始值
t = it #最终的值
while 1 > 0:
    t = t*it
    num = num + 1
    if t < pow(10,pl):
        break
print(num)


5


## 8. Find Normalized Eigenvector Given Diagonalization

### inverse

In [72]:
import numpy as np
import numpy.linalg as la
p = 1 # required norm
t = [4,9,14]

# inverse : 找最小的eigenvalue里面 对应的eigenvector
norm = np.array(t).T
norm1 = la.norm(norm, p)
ans = norm/norm1
print(ans)

[0.14814815 0.33333333 0.51851852]


In [1]:
# inf norm
import numpy as np
import numpy.linalg as la
t = [4,13,8]

# inverse : 找最小的eigenvalue里面 对应的eigenvector
norm = np.array(t).T
norm1 = la.norm(norm, np.inf)
ans = norm/norm1
print(ans)

[0.30769231 1.         0.61538462]


### power

In [73]:
import numpy as np
import numpy.linalg as la
p = 1 # required norm
t = [2,13,16]

# power : 找最大的eigenvalue里面 对应的eigenvector
norm = np.array(t).T
norm1 = la.norm(norm, p)
ans = norm/norm1
print(ans)

[0.06451613 0.41935484 0.51612903]


## 9 Condition Number of a Diagonal Matrix

### infinite norm

In [82]:
import numpy as np
a = np.array([4.6,-4.0,1.1,-3.6])
p = max(abs(a)) # \\A\\
n = max(abs(1/a)) #\\ A\\^ -1
c = p*n
c

4.181818181818182

### 2-norm

In [10]:
import numpy as np
import numpy.linalg as la
A = np.zeros([5,5])
A[0,0] = 2.9
A[1,1] = 1
A[2,2] = 2.1
A[3,3] = -2.1
A[4,4] = 2.9
norm = la.norm(A,2)
AA = la.inv(A)
normA = la.norm(AA,2)
c = norm*normA
c

2.9

## 10.Finding the Eigenvalues of Transformed Matrices

In [84]:

'''
find eigenvalue of ((c1*A-c2*I)^(-1))
'''
a1e = 8 #eigen1
a2e = 3 #eigen2
c1 = 2
c2 = 1
p = 2

e1 = 1/(c1*a1e - c2)
e2 = 1/(c1*a2e - c2)

print(max(e1, e2))

0.2


## 11. Estimating the Error of Shifted Inverse Iteration

In [7]:
'''
s1: |smallest eigen|
s2: |2nd smallest eigen|
p: power of iteration
s: shift
e1: without shift
e2: with shift
'''
import numpy as np
import numpy.linalg as la
s1 = 2
s2 = -5
u = np.array([-1,0,1])
x0 = np.array([-1,-1,-1])
p = 3
s = 1

ini = la.norm(x0-u,np.inf)

e1 = ini*pow(abs(s1)/abs(s2),p) 
e2 = ini*pow(abs(s1 - s)/abs(s2 - s),p) 
print("error in (a)", e1, "\nerror in (b)", e2)

error in (a) 0.12800000000000003 
error in (b) 0.009259259259259257


## 12  Similarity Transformation of a Matrix 5.1

In [54]:
import numpy as np
import numpy.linalg as la
import scipy.linalg as sc
#S1: get value
A = np.array([
    [2,-1],
    [0,1]
])
p = 1

w,v = la.eig(A)
#S2: to normalize
v1 = v[:,0] #vector1
v2 = v[:,1] #vecctor2
n1 = la.norm(v1,p)
n2 = la.norm(v2,p)
v1 = v1/n1
v2 = v2/n2
vv = np.vstack((v1, v2)).T
print( w,"\n",vv)


[2. 1.] 
 [[1.  0.5]
 [0.  0.5]]


## 13 Power Iteration Convergence

In [48]:
import numpy as np
e1 = 6
e2 = -4
e3 = 2
z1 = np.array([1,5,2])
z2 = np.array([1,5,6])
z3 = np.array([1,4,9])
a = 0
b = 2
c = 3
x0 = a*z1 + b*z2 + c*z3
ex0 = a*e1 + b*e2 + c*e3
print(x0,ex0)

[ 5 22 39] -2


## 14. Result of Normalized Power, Inverse, and Shifted Inverse Iteration

In [49]:
import numpy as np
import numpy.linalg as la
n = np.array([14,14,16])
p = 1
m = la.norm(n,p)
result = n/m
result

array([0.31818182, 0.31818182, 0.36363636])

## C1 Converting a CSR Matrix to a Dense Matrix

In [ ]:
import numpy as np
rp = A_csr.indptr
ci = A_csr.indices
data = A_csr.data
shape = A_csr.shape
A = np.zeros(shape)
#S1 get how many elements in each row
rnum = np.zeros(len(rp) - 1)
for i in range(len(rp) - 1):
    rnum[i] = rp[i+1] - rp[i]

#S2 use value
acc = 0
for j in range(len(rnum)): # row 
    remain = int(rnum[j]) #number of remain elements
    acc = rp[j] # the number of used elements
    for k in range(remain):
        A[j][ci[k+acc]]= data[k+acc] # k + acc 

## C2: Estimate Digits

In [2]:
# 1.12 Estimating the Number of Correct Digits
import numpy as np
import numpy.linalg as la
from decimal import *
x = la.solve(A,b) #x right
'''
cond = la.cond(A)
d = Decimal(cond)
correct_digits = abs(d.as_tuple().exponent)
print(correct_digits)
print(d)
'''

NameError: name 'A' is not defined

## C3: The magic pot

In [ ]:
# 1 10 The magic pot experiment
import numpy as np
import numpy.linalg as la

temp = A@comp1
k = comp1[missing_col_index] # get k

A_complete = A
#get a, b, c, d, f
for i in range(6):
    if i != missing_row_index: #exclude other
        A_complete[i][missing_col_index] = (comp2[i] - temp[i])/k 

for i in range(6):
    t = 1 - sum(A_complete[0:,i])
    A_complete[missing_row_index][i] = t
    


def final_comp(A):
    #make initial arra: sum = 1
    x = A.shape[0]
    v = np.zeros([x])
    for i in range(x):
        v[i] = 1/x
    #keep produce    
    con = A@v
    for k in range(100000):
        con = A@con
        
    return con

## C4: Train Stations

In [1]:
# 2 10 Traveling by Train
import numpy as np 
#S1 make matrix by problem
mat = np.array([
    [0, 0.25, 0.25, 0.25, 0.25],
    [0.5, 0, 0, 0.5, 0],
    [0.5, 0.5, 0, 0, 0],
    [0, 0, 0.5, 0, 0.5],
    [0, 1, 0, 0, 0]
    ])
mat = mat.T
#S2 make start position
start = np.zeros(5)
start[0] = 1
#S3 produce
prob = mat@start
for i in range(100000):
    prob = mat@prob

## C5: Investigating Conditioning

In [ ]:
# 2 11 Conditioning and relative error
import numpy as np
import numpy.linalg as la
#2-norm
err_xhat = xtrue - xhat
rel_err_xhat = la.norm(err_xhat, 2)/la.norm(xtrue, 2)

#delta y
y = A@xtrue
dy = A@err_xhat 
rel_err_Axhat = la.norm(dy, 2)/la.norm(y, 2)

cond_A = la.cond(A)
bound_rel_err_Axhat	= rel_err_xhat*cond_A