## 1.1 Finite Difference: Calculation R -> R
#### 省evaluation: forward & backward
#### best error bound: central

In [40]:
import numpy as np
import numpy.linalg as la
import sympy as sym
import math
from math import e

#change 
def f(t):
    return -np.log(t) #去掉c
xhat = 0.7  # point where we want to find the approximation
h = 0.02   # initial perturbation / step size
#change end

#!!!看清题目用什么method： 选好
#forward
fval = f(xhat)  # we only need to evaluate this once!
# one function evaluation per each perturbation size
dfapprox1 = ( f(xhat+h) - fval ) / h  
print("for")
print(dfapprox1)

#backward
dfapprox2 = ( fval - f(xhat-h) ) / h 
print("back")
print(dfapprox2)

#central
dfapprox3 = ( f(xhat+h) - f(xhat-h) ) / (2*h)
print("central")
print(dfapprox3)

for
-1.4085438483348172
back
-1.4493768436626169
central
-1.428960345998717


## 1.2 Finite Difference Gradient
#### 注意for/back

In [6]:
import numpy as np
import numpy.linalg as la
import sympy as sym
import math
from math import e
#change
def fn(xvec):
    x = xvec[0]
    y = xvec[1]
    z = xvec[2]
    return x*z**2 + 2*x*z
i = 1 # E: 0; F: 1
rxs = [1,1,1] #approximation at point rxs
h = 0.1

n = 3   #row_num in E / vector_size
#change end


##审题！！！:  using "forward" finite difference method
#finite diff method to fin Jacobian
def forward(rxs, h, fn):
    Jac = np.zeros(n)
    fvaln = fn(rxs)
    for i in range(n):
        xfd = rxs.copy()
        xfd[i] += h
        # column i
        Jac[i] = (fn(xfd) - fvaln)/h
    E = -Jac
    return E

def backward(rxs, h, fn):
    Jac = np.zeros(n)
    fvaln = fn(rxs)
    for i in range(n):
        xfd = rxs.copy()
        xfd[i] -= h
        # column i
        Jac[i] = (fvaln -fn(xfd))/h
    E = -Jac #要求为负！！！！！！！！！！
    return E
def central(rxs, h, fn):
    Jac = np.zeros(n)
    fvaln = fn(rxs)
    for i in range(n):
        xfd1 = rxs.copy()
        xfd2 = rxs.copy()
        xfd1[i] -= h
        xfd2[i] += h
        # column i
        Jac[i] = (fn(xfd2) -fn(xfd1))/(2*h)
    E = -Jac #要求为负！！！！！！！！！！
    return E

print("forward")
print(forward(rxs, h, fn)*(-1)**i)
print("backward")
print(backward(rxs, h, fn)*(-1)**i)
print("central")
print(central(rxs, h, fn)*(-1)**i)

forward
[3.  0.  4.1]
backward
[3.  0.  3.9]
central
[3. 0. 4.]


## 2.1.1  One Step of Solving 1D Equations
## Perform one step of Secant method
## Perform Two Steps of Bisection
Newton, secant, bisection  
#### (df) root, 1d(1 equation), 1 variable, 1 or n steps

In [4]:
import sympy as sp
def Newton_1D_step(x_prev, f_str, var_str):
    '''
    Given x_k, string representation of function, and string representation of variable
    Return the numerical value of x_{k+1}
    '''
    f = sp.sympify(f_str)
    var = sp.symbols(var_str)
    df = sp.diff(f, var)
    print(df)
    x_next = x_prev - f.subs(var, x_prev) / df.subs(var, x_prev)
    return float(x_next)

def Newton_1D_step_aux(x_prev, f, df, var):
    '''
    Given x_k, function, differentiation of the function, and the variable
    Return the numerical value of x_{k+1}
    Operate as a lighter weighted version of Newton_1D_step
    '''
    return float(x_prev - f.subs(var, x_prev) / df.subs(var, x_prev))

def Newton_1D(x_0, f_str, var_str, err_bound):
    '''
    Given initial value x_0, string representation of function, string representation of variable
    as well as the error bound
    Return the number of iterations it takes to get to the error bound
    And the final value
    '''
    f = sp.sympify(f_str)
    var = sp.symbols(var_str)
    df = sp.diff(f, var)
    x_curr = x_0
    iterations = 0
    while abs(float(f.subs(var, x_curr))) > err_bound:
        x_curr = Newton_1D_step_aux(x_curr, f, df, var)
        iterations += 1
    return iterations, x_curr

def secant_1D_step(x_prev0, x_prev1, f_str, var_str):
    '''
    Given x_{k-1}, x_{k}, string representation of function, and string representation of variable
    Return the numerical value of x_{k+1}
    '''
    f = sp.sympify(f_str)
    var = sp.symbols(var_str)
    x_next = x_prev1 - f.subs(var, x_prev1) / ((f.subs(var, x_prev0) - f.subs(var, x_prev1)) / (x_prev0 - x_prev1))
    return float(x_next), (f.subs(var, x_prev0) - f.subs(var, x_prev1)) / (x_prev0 - x_prev1)
def bisection_1D_step(left, right, f_str, var_str):
    f = sp.sympify(f_str)
    var = sp.symbols(var_str)
    mid = (left + right) / 2
    if float(f.subs(var, left) * f.subs(var, mid)) < 0:
        right = mid
    else:
        left = mid
    return left, right
'''
sin(x/6)
'''
f_str = 'cos(x)'
var_str = 'x'

#Newton
nx1 = 0.25 

#Secant
sx0 = 1
sx1 = 0

#biscant
a = -3
b = 8
j = 2 # bisc iteration

newton_res = Newton_1D_step(nx1, f_str, var_str)

secant_res = secant_1D_step(sx0, sx1, f_str, var_str)

bi = []
temp = bisection_1D_step(a, b, f_str, var_str)
bi.append(temp)
for i in range(j - 1):
    temp = bisection_1D_step(temp[0], temp[1], f_str, var_str)
    bi.append(temp)

print(newton_res)
print("----Secant----")
print("dfap:", secant_res[1])
print("x2 :", secant_res[0])
print("----biscant----")
print("step1")
print(bi[0])
print("step2")
print(bi[1])

-sin(x)
4.1663173646459395
----Secant----
dfap: -1 + cos(1)
x2 : 2.1753426496700214
----biscant----
step1
(2.5, 8)
step2
(2.5, 5.25)


## 2.1.2 Perform Two Steps of Newton's Method
#### root(df); 1d; 1 variable

In [33]:
import sympy as sp
def Newton_1D_step(x_prev, f_str, var_str):
    '''
    Given x_k, string representation of function, and string representation of variable
    Return the numerical value of x_{k+1}
    '''
    f = sp.sympify(f_str)
    var = sp.symbols(var_str)
    df = sp.diff(f, var)
    x_next = x_prev - f.subs(var, x_prev) / df.subs(var, x_prev)
    return float(x_next)

def Newton_1D_step_aux(x_prev, f, df, var):
    '''
    Given x_k, function, differentiation of the function, and the variable
    Return the numerical value of x_{k+1}
    Operate as a lighter weighted version of Newton_1D_step
    '''
    return float(x_prev - f.subs(var, x_prev) / df.subs(var, x_prev))

def Newton_1D(x_0, f_str, var_str, err_bound):
    '''
    Given initial value x_0, string representation of function, string representation of variable
    as well as the error bound
    Return the number of iterations it takes to get to the error bound
    And the final value
    '''
    f = sp.sympify(f_str)
    var = sp.symbols(var_str)
    df = sp.diff(f, var)
    x_curr = x_0
    iterations = 0
    while abs(float(f.subs(var, x_curr))) > err_bound:
        print(iterations, " ", x_curr)
        x_curr = Newton_1D_step_aux(x_curr, f, df, var)
        iterations += 1
    return iterations, x_curr
x0 = 0
fx = 'x**3 + 4*x - 1'
p = -3
Newton_1D(x0, fx, 'x', 10**p)

0   0
1   0.25


(2, 0.2462686567164179)

## 2.1.3 Determine the length of the interval
#### bisection

In [9]:
# Bisection Method
# Q: the length of the interval after ? iterations of bisection
import numpy as np

#change
L = -7
R = 12
iteration_num = 4 #  after ? iterations of bisection

def function(x):
    return (x-4)**3
#change end

def bisetic(inter, iteration_num):
    a = inter[0]
    b = inter[1]
    interval_length = 0
    if (a >= b or np.sign(function(a)) == np.sign(function(b))):
        return None
    fa = function(a)
    for i in range(iteration_num):
        m = (a+b)/2
        fm = function(m)  
        if  np.sign(fa) == np.sign(fm):
            a = m 
            fa = fm 
        else:
            b = m
        interval_length = np.abs(a-b)
    return interval_length

interval = [L, R]
bisetic(interval, iteration_num)

1.1875

## 2.2(a) Newton Solve
#### root(df), nd(2 equations), 2 variables, 1 step
NewtonND-triangular  
Jocobian & x1

In [12]:
import numpy as np
import numpy.linalg as la
import sympy as sp
#s1 build f
def subs_all(formula, variables, values):
    '''
    helper function for Jocabian
    You know what, it's getting to the point where this function
    is necessary
    '''
    result = formula
    for i in range(len(values)):
        result = result.subs(variables[i], values[i])
    return float(result.evalf())

def calculated_jacobian(fs, variables, x_k):
    '''
    fs need to EQUAL TO ZERO!
    '''
    size = len(fs)
    result = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            result[i][j] = subs_all(sp.diff(fs[i], variables[j]), variables, x_k)
    return result

def newton_nd_step(x_prev, f_strs, var_str):
    '''
    Given x_k, string of functions equal to 0, and string for variables: 
    calculate the parameter for the next iteration of Newton's method 
    for solving ND non-linear system of equations
    '''
    fs = [sp.sympify(f_str) for f_str in f_strs]
    variables = sp.symbols(var_str)
    jac = calculated_jacobian(fs, variables, x_prev)
    f_vals = np.array([subs_all(f, variables, x_prev) for f in fs])
    s = la.solve(jac, -1*f_vals)
    return jac, x_prev+s

# Workspace
'''
x0
fv: f vector
variable
'''

f1 = '-3*x**2 + -3*x + 3 + 2*y**2 + 2*y + 3*x*y'
f2 = '3*x**2 - 2*x - 1 + 2*y**2 - 2*y - 2*x*y'


f3 = '4*x**3 + 2*y**4 - 6'
f4 = '6*x**2 + 3*y -5'

x0 = [-1, 1]
fv = [f1, f2]
var = 'x y'
newton_nd_step(x0, fv, var)


(array([[  6.,   3.],
        [-10.,   4.]]),
 array([-0.96296296, -0.40740741]))

## 2.2(b) Newton Solve 2 
#### root(df), nd(2 equations), 2 variable, 1 step, get x1

In [1]:
import numpy as np
import numpy.linalg as la
import sympy as sym
x1, x2 = sym.symbols('x1 x2')
# x, y, z = sym.symbols('x y z')

#change
#the function should be as the form: .... = 0
fnt = np.array([3*x1*x2-4, x1**3+(x2**2)+5])
rxs = [0, 2]  #initial guess x0
#change end


#find J
n = fnt.shape[0]
J = np.zeros((n,n))
xs = [x1, x2]
# xs = [x, y, z]
for i in range(n):
    for j in range(n):
        diff = sym.diff(fnt[i], xs[j])
        J[i,j] = diff.evalf(subs={xs[0]:rxs[0], xs[1]:rxs[1]})

# Newton's method: the resulting approximate solution after 1 iteration 
f = np.zeros_like(fnt)
for i in range(len(fnt)):
    f[i] = (fnt[i].evalf(subs={xs[0]:rxs[0], xs[1]:rxs[1]}))
    
f = f.astype(np.float64)
rxs + la.solve(J, -f)

array([ 0.66666667, -0.25      ])

## 3.1.1(a) Perform One Step of Golden Section Search
#### op 1d

In [12]:
import numpy as np

# change
def f(x):
    return (x-6.2)**4
a = -3 #LB of the starting interval
b = 12  #UB of the starting interval
iteration_num = 1 # next iteration
# change end


brackets = []
tau = (np.sqrt(5)-1)/2
m1 = a + (1 - tau) * (b - a)
m2 = a + tau * (b - a)

f1 = f(m1)
f2 = f(m2)
interval = np.abs(m1-m2)  
x1 = m1
x2 = m2
a0 = a
b0 = b

for i in range(iteration_num):
    if  f1>f2:
        a0 = x1
        x1 = x2
        f1 = f2
        h_k = b0-a0
        x2 = a0 + tau * h_k
        f2 = f(x2)
    else:
        b0 = x2
        x2 = x1
        f2 = f1
        h_k = b0-a0
        x1 = a0 + (1-tau) * h_k
        f1 = f(x1)
    brackets.append([a,a0,b0,b])
    interval = np.abs(a0-b0) #所求
    
print(brackets[0][1], brackets[0][2])

2.7294901687515765 12


## 3.1.1(b) Determine the length of the interval after one iteration
## Perform One Step of Golden Section Search
#### op 1d

In [2]:
import numpy as np
def f(x):
    return (x - 3.7)**2
a = -2
b = 5

brackets = []
gs = (np.sqrt(5) - 1) / 2
m1 = a + (1 - gs) * (b - a)
m2 = a + gs * (b - a)
epsilon = 1e-5

# Begin your modifications below here
f1 = f(m1)
f2 = f(m2)
h = b-a
if f1 > f2:
    a = m1
    m1 = m2
    f1 = f2
    h *= gs
    m2 = a + gs * h
    f2 = f(m2)
    brackets.append([a, m1, m2, b])
else:
    b = m2
    m2 = m1
    f2 = f1
    h *= gs
    m1 = a + (1 - gs) * h
    f1 = f(m1)
    brackets.append([a, m1, m2, b])
print(a)
print(b)
print(b-a)

0.6737620787507357
5
4.326237921249264


## 3.1.2 Carrying out Newton steps
#### optimization(ddf)/minimum; 1d; 1 variable; 1 step

In [13]:
#-e^(-x^2)
import numpy as np
def df(x):
    return 2*x*np.exp(-x**2)
def d2f(x):
    return 2*np.exp(-x**2)*(1-2*x**2)
x = 0.4 
for i in range(1):
    dfx = df(x)
    d2fx = d2f(x)
    xnew = x - dfx / d2fx
    if np.abs(xnew-x) < 1e-8:
        break
    x = xnew 
print(x)

-0.18823529411764717


In [10]:
#cosx 
import numpy as np
def df(x):
    return -1*np.sin(x)
def d2f(x):
    return -1*np.cos(x)

x = 0.45
for i in range(1):
    dfx = df(x)
    d2fx = d2f(x)
    xnew = x - dfx / d2fx
    if np.abs(xnew-x) < 1e-8:
        break
    x = xnew 
print(x)

-0.033055065616578394


In [23]:
#5*cosx**5 
import numpy as np
def df(x):
    return -25*np.cos(x)**4*np.sin(x) 
def d2f(x):
    return -25*(np.cos(x)**5 - 4*np.sin(x)**2*np.cos(x)**3)

x = 0.25
for i in range(1):
    dfx = df(x)
    d2fx = d2f(x)
    xnew = x - dfx / d2fx
    if np.abs(xnew-x) < 1e-8:
        break
    x = xnew 
print(x)

-0.09542914752227516


In [3]:
#-2e^(-6x^2)
import numpy as np
def df(x):
    return 24*x*np.exp(-6*x**2)
def d2f(x):
    return 24*np.exp(-6*x**2)*(1-12*x**2)
x = 0.4 

for i in range(1):
    dfx = df(x)
    d2fx = d2f(x)
    xnew = x - dfx / d2fx
    if np.abs(xnew-x) < 1e-8:
        break
    x = xnew 
print(x)

0.8347826086956521


## 3.2.1 N-Dimension Optimization using Steepest Descent
#### op nd
s0 = -df(x)  
x1 = x0 + alpha* s0

In [11]:
import numpy as np
import numpy.linalg as la
import sympy as sp
import scipy.optimize as sopt
def f(x):
    a = x[0]
    b = x[1]
    return 11*a**2 + 11*a*b +11*b**2 + 12*np.sin(b)**2 + 11*np.cos(a*b)

def df(x):
    y = x[1]
    x = x[0]
    
    return np.array([22*x + 11*y - 11*np.sin(x*y)*y,
                     11*x + 22*y + 12*2*np.sin(y)*np.cos(y)-11*np.sin(x*y)*x ])


      
x = np.array([-3, 3])
alpha = 0.02

s = -df(x)
xnew = x + alpha * s
print("s0 is ", s)
print("x1 is ", xnew)
        


s0 is  [ 19.40008999 -16.04710401]
x1 is  [-2.6119982   2.67905792]


## 3.2.2 Optimization ND NewtonMethod one step
## Carrying out Newton steps (n-dimensional)
##  Optimization ND NewtonMethod get step: H, s0
#### grad, hessian, x1, s0
#### op ddf, 1d(1 equation), 2 variables, 1 step

In [5]:
import numpy as np
import numpy.linalg as la
import sympy as sp
def gradient(formula, symbols, values=None):
    '''
    Given a SymPy formula and variables
    Find its analytic gradient without substituion
    as a list of SymPy formulae or numerical gradient
    if values specified
    '''
    size = len(symbols)
    gradient = []
    for i in range(size):
        gradient.append(formula.diff(symbols[i]))
        
    if values == None:
        return gradient

    # Make sure you don't mess up the analytical gradient
    g_copy = gradient.copy()
    gradient_at = []
    for i in range(len(g_copy)):
        for j in range(len(symbols)):
            g_copy[i] = g_copy[i].subs(symbols[j], values[j])
        gradient_at.append(float(g_copy[i].evalf()))
    return gradient_at
def subs_all(formula, variables, values):
    '''
    You know what, it's getting to the point where this function
    is necessary
    '''
    result = formula
    for i in range(len(values)):
        result = result.subs(variables[i], values[i])
    return float(result.evalf())
def hessian(gradient, symbols, values=None):
    '''
    Given an analytic gradient and variables
    Calculate its analytic Hessian
    or numerical Hessian if values are specified
    '''
    size = len(symbols)
    hessian = []
    for i in range(size):
        hessian.append([0]*size)
    for i in range(size):
        for j in range(size):
            hessian[i][j] = gradient[i].diff(symbols[j])
            
    if values == None:
        return hessian
    
    hessian_at = hessian.copy()
    size = len(hessian)
    for i in range(size):
        for j in range(size):
            hessian_at[i][j] = subs_all(hessian_at[i][j], symbols, [float(v) for v in values])
#             for k in range(len(symbols)):
#                 hessian_at[i][j] = hessian_at[i][j].subs(symbols[k], values[k])
#             hessian_at[i][j] = float(hessian_at[i][j].evalf())
    return hessian_at
def newton_nd_optimization_crude_step(formula, symbols, x_prev):
    x_prev = list(x_prev)
    grad = gradient(formula, symbols)
    neg_gradient_at = -1 * np.array(gradient(formula, symbols, values=x_prev))
    hes_at = np.array(hessian(grad, symbols, values=x_prev))
    return np.array(x_prev) + la.solve(hes_at, neg_gradient_at)

form = sp.sympify('8*x**2 + 3*x*y + 8*y**2 + 10*E**(7*x*y) + 7*(sin(y)**2) + 14*cos(x*y)')
form = sp.sympify("6*x**4 + 3*y**2")
#form = sp.sympify('E**(9*x) + 8*cos(y)')
symbols = sp.symbols('x y')
values = [1, 3]

grad = gradient(form, symbols, values)
hes = hessian(gradient(form, symbols), symbols, values)
x_1 = newton_nd_optimization_crude_step(form, symbols, values)
step = np.array(x_1) - np.array(values)
print("grad is ", grad)
print("hes is ", hes)
print("x1 is", x_1)
print("s0 is", step)

grad is  [24.0, 18.0]
hes is  [[72.0, 0.0], [0.0, 6.0]]
x1 is [0.66666667 0.        ]
s0 is [-0.33333333 -3.        ]


## Reserve

## C1 Finite Difference

In [8]:
import numpy as np
'''
S0: 方程
S1：choice method
'''
def f(x):
    return x[0]**2 + x[1]**5 + x[2]*x[5] + x[3]*x[5] +x[4]*x[5] + x[5]**4 + x[6]**4

n = 7   
def forward(rxs, h, f):
    Jac = np.zeros(n)
    fvaln = f(rxs)
    for i in range(n):
        xfd = rxs.copy()
        xfd[i] += h
        # column i
        Jac[i] = (f(xfd) - fvaln)/h
    return Jac
approx_gradient = forward(xvec, 0.5, f)

## C2 Find the time to meet using Newton's method
### When will they meet?
root; 1d; find all xi

In [ ]:
import numpy as np
import sympy as sp
'''
dis = 170
xt + xj = 170
'''
def Newton_1D_step_aux(x_prev, f, df, var):
    '''
    Given x_k, function, differentiation of the function, and the variable
    Return the numerical value of x_{k+1}
    Operate as a lighter weighted version of Newton_1D_step
    '''
    return float(x_prev - f.subs(var, x_prev) / df.subs(var, x_prev))

def Newton_1D(x_0, f_str, var_str, err_bound):
    '''
    Given initial value x_0, string representation of function, string representation of variable
    as well as the error bound
    Return the number of iterations it takes to get to the error bound
    And the final value
    '''
    f = sp.sympify(f_str)
    var = sp.symbols(var_str)
    df = sp.diff(f, var)
    x_curr = x_0
    iterations = 0
    all_guess = []
    while abs(float(f.subs(var, x_curr))) > err_bound:
        x_curr = Newton_1D_step_aux(x_curr, f, df, var)
        all_guess.append(x_curr)
        iterations += 1
    return iterations, x_curr, all_guess

f_str = '(x**3)/60 + x**2 + 30*cos(x) + 20*x - 170'
var_str = 'x'
t = Newton_1D(t_initial, f_str, var_str, epsilon)[2]

## C3 Control the Temperature
### How much wood is needed?

In [ ]:
import numpy as np
'''
bisection method: shift 375 
reach 375 degree
w -> degreee
'''
def bisetic(left, right, function):
    a = left
    b = right
    List = [(a,b)]
    fa = function(a)
    
    while True:
        m = (a+b)/2
        fm = function(m)
        
        if (np.abs(fm - 375) < epsilon):
             return m, List
        if  np.sign(fa - 375) == np.sign(fm - 375):
            a = m 
            fa = fm 
            List.append((a,b))
        else:
            b = m
            List.append((a,b))
    return None
weight, intervals = bisetic(0, max_wood, get_temperature)

## C4 Newton's Method
root; nd  
collect all xi

In [ ]:
import numpy as np
import numpy.linalg as la

def f(w):
    x, y, z = w
    return np.array([
        16*x**4 + 16*y**4 + z**4 - 16,
        x**2    + y**2    + z**2 - 3,
        x**3    - y])
def df(w):
    x, y, z = w
    return np.array([
        [64*x**3, 64*y**3, 4*z**3],
        [2*x    , 2*y    ,2*z],
        [3*x**2, - 1, 0]])


guesses = np.zeros((5,3))

# Initial guess, don't save this in output
w = np.array([1.,1.,1.])
for i in range(5):
    s = -la.solve(df(w), f(w))
    w = w + s
    guesses[i] = w

## C5

## C6